sudo: true
dist: trusty
addons:
  apt:
    packages:
    - lmodern
    - texlive-fonts-extra
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-luatex
    - texlive-science
    - texlive-xetex
env:
  global:
  - GH_REF: git@github.com:ecsedigergo/MScThesis.git
  - GH_TOKEN: ICJw9HgV8SBxG94lUyoYNcXXsu15b5to8+Z6EhH0MchDHj7xB+d0kd6ucTFHJI32YdO4VFWJR6i5eWFcIaEKnpj1b0kpYdSFdoK9SZCe4vb3HmI3pRF16NSvkp/MdKG5nS20D2He+Y9U+fhLn7lvso11nmXGmtHVBqLzgmX1xMfZ7ElHQhpb2MIrJnbbwg4hozkNbjw1TNsiVwYRu2DgFzYHkPQkN9gNd7S1ORN2jL7DuMCJAoO17FtH/98aAsjEstTFbPCcH6tAt4xgTpnz8eWCwEjXVhBNeg8xcIgul+Psp7O5px43Y+K8sS+fVPcnRCGVicW6e2F13TVyBG4u8KFKwcuLj04kxv3n3WUg1J03gXP0H/dQhLgKDE6UmgKsZ+iywjYVgZNTCPr5yEjiiwQGgvrRRjc3WFzY4bOdoHVErmqraLTgU9rwwd+mCAsSAaSFxtf95U/149jcByFPxpZDa86Uq3/p/VT15ty2j4od2OoBft2VMu/a6QpjmRM8uJQOJZHjiD5BsZdSDrv5QYJXQOaadNu5xOVNQFibdjGLdaymZ953HHIDzX17uLTarsMjoBxAM5Ng5cTwXzUi3oFj7H0mUpr9QpKHbAI55W6enKB3CBpIezGr+fpC+FnY+xnGyyFXCWALkyZTtoKq9Fxow7lrzaKjH/+fMob5WE0=
script:
- cd src
- kpsewhich language.dat.lua
- sudo cp lua/language.dat.lua `kpsewhich language.dat.lua`
- make test
- cd ..
- if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then ./deploy.sh;  fi
notifications:
  slack: ftsrg:qnSMPdAdgpSj9vVxcl2AB2qU
  on_success: change
  on_failure: always